# Generated by Django 4.1.5 on 2023-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('iduser', models.AutoField(db_column='iduser', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=8, null=True)),
            ],
            options={
                'db_table': 'SignIn',
                'managed': False,
            },
        ),
    ]
